### ISSUE TITLE
Fix Sublime Text 3 Build 3088 php icon display.

### ISSUE THREAD

**Issue by momoca** [buymeasoda/soda-theme#202]
[Sublime Text Build 3088 x64]\Packages\PHP.sublime-package\PHP.sublime-syntax (line:12)
replace:`scope: embedding.php` to `scope: source.php`
[Sublime Text Build 3088 x64]\Packages\PHP.sublime-package\PHP.tmLanguage
replace:
```xml
	<key>hidden</key>
	<true/>
```
to
```xml
	<key>hidden</key>
	<true/>
	<key>fileTypes</key>
	<array>
		<string>php</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!.*(?&lt;!-)php[0-9]{0,1}\b</string>
```

**Comment by pryley** [comment]
Well this isn't an issue with the soda-theme, rather a bug in Sublime Text 3 (build 3103).

Thanks for the fix though. I didn't see the `PHP.tmLanguage` file, but editing `PHP.sublime-syntax` did the trick. 

If anyone on a Max is confused by the above directions:

1. You are editing the `PHP.sublime-package` which is found inside the app (right-click Sublime Text.app and `Show Package contents`.

2. `PHP.sublime-package` is simply a zip file with `.sublime-package` as the extension instead of `.zip`. Here is the full path: 
`/Applications/Sublime Text.app/Contents/Resources/Packages/PHP.sublime-package`

3. Copy `PHP.sublime-package` to another directory, press `⌘I` to open the info window and change the extension to `.zip`, uncompress and edit the `PHP.sublime-syntax` file as shown above.

4. Once you have made the changes, select all files and compress to a single archive.

5. Select the new archive, press `⌘I` to rename it to `PHP.sublime-package`, and copy it back into the app, replacing the old one.

6. Restart Sublime Text.

**Comment by timothevs** [comment]
Doesn't seem to fix it in Build 3105. The sidebar PHP icons are still missing. The Sublime-syntax seems to be in YAML. 

Any insights into how best to fix this in x3105?
